version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/usr/src/app
    command: cd react-app && yarn start
    ports:
      - 3000:3000
